unit DMVenda_p;

interface

uses
  SysUtils, Classes, FMTBcd, DB, DBClient, Provider, SqlExpr, JvMemoryDataset;

type
  TDMVenda = class(TDataModule)
    qConfG: TSQLQuery;
    dspConfG: TDataSetProvider;
    cdsConfG: TClientDataSet;
    dsConfG: TDataSource;
    qEmpresa: TSQLQuery;
    dspEmpresa: TDataSetProvider;
    cdsEmpresa: TClientDataSet;
    cdsEmpresaCDEMPRESA: TIntegerField;
    cdsEmpresaRAZAO_SOCIAL: TStringField;
    cdsEmpresaAPELIDO: TStringField;
    cdsEmpresaENDERECO: TStringField;
    cdsEmpresaNUMERO: TStringField;
    cdsEmpresaBAIRRO: TStringField;
    cdsEmpresaCIDADE: TStringField;
    cdsEmpresaCEP: TStringField;
    cdsEmpresaUF: TStringField;
    cdsEmpresaCNPJ: TStringField;
    cdsEmpresaIE: TStringField;
    cdsEmpresaLOGO: TBlobField;
    cdsEmpresaSITE: TStringField;
    cdsEmpresaTELEFONE: TStringField;
    dsEmpresa: TDataSource;
    qItensTMP: TSQLQuery;
    dspItensTMP: TDataSetProvider;
    cdsItensTMP: TClientDataSet;
    dsItensTMP: TDataSource;
    qConFiscal: TSQLQuery;
    dspConFiscal: TDataSetProvider;
    cdsConFiscal: TClientDataSet;
    dsConFiscal: TDataSource;
    cdsConFiscalCDCONFIG_FINANCEIRA: TIntegerField;
    cdsConFiscalIMPRESSORA_FICAL: TIntegerField;
    cdsConFiscalTIPO_IMPRESSORA: TStringField;
    QEmpty: TSQLQuery;
    IntegerField1: TIntegerField;
    IntegerField2: TIntegerField;
    IntegerField3: TIntegerField;
    DateField1: TDateField;
    TimeField1: TTimeField;
    SingleField1: TSingleField;
    FMTBCDField1: TFMTBCDField;
    FMTBCDField2: TFMTBCDField;
    SingleField2: TSingleField;
    SingleField3: TSingleField;
    FMTBCDField3: TFMTBCDField;
    IntegerField4: TIntegerField;
    IntegerField5: TIntegerField;
    StringField1: TStringField;
    SingleField4: TSingleField;
    StringField2: TStringField;
    StringField3: TStringField;
    IntegerField6: TIntegerField;
    IntegerField7: TIntegerField;
    qMovimenta: TSQLQuery;
    dspMovimenta: TDataSetProvider;
    cdsMovimenta: TClientDataSet;
    dsMovimenta: TDataSource;
    qPedidosPag: TSQLQuery;
    qPedidosPagCDPEDIDOS_PAGAMENTO: TIntegerField;
    qPedidosPagCDPEDIDO: TIntegerField;
    qPedidosPagCDPAGAMENTO: TIntegerField;
    qPedidosPagVALOR_PAGO: TFMTBCDField;
    qPedidosPagPAGAMENTO: TStringField;
    cdsPedidosPag: TClientDataSet;
    cdsPedidosPagCDPEDIDOS_PAGAMENTO: TIntegerField;
    cdsPedidosPagCDPEDIDO: TIntegerField;
    cdsPedidosPagCDPAGAMENTO: TIntegerField;
    cdsPedidosPagVALOR_PAGO: TFMTBCDField;
    cdsPedidosPagPAGAMENTO: TStringField;
    dspPedidosPag: TDataSetProvider;
    dsPedidosPag: TDataSource;
    qTP: TSQLQuery;
    cdsTP: TClientDataSet;
    cdsTPCDPAGAMENTO: TIntegerField;
    cdsTPPAGAMENTO: TStringField;
    dspTP: TDataSetProvider;
    dsTP: TDataSource;
    qTroco: TSQLQuery;
    jvmPagamento: TJvMemoryData;
    dsPagamento: TDataSource;
    qCaixa: TSQLQuery;
    qCaixaCDCAIXA: TIntegerField;
    qCaixaDATA: TDateField;
    qCaixaCDUSUARIO: TIntegerField;
    qCaixaDESCRICAO: TStringField;
    qCaixaCREDITO: TFMTBCDField;
    qCaixaDEBITO: TFMTBCDField;
    qCaixaNUMERO_PDV: TIntegerField;
    qCaixaNOME: TStringField;
    cdsCaixa: TClientDataSet;
    cdsCaixaCDCAIXA: TIntegerField;
    cdsCaixaDATA: TDateField;
    cdsCaixaCDUSUARIO: TIntegerField;
    cdsCaixaDESCRICAO: TStringField;
    cdsCaixaCREDITO: TFMTBCDField;
    cdsCaixaDEBITO: TFMTBCDField;
    cdsCaixaNUMERO_PDV: TIntegerField;
    cdsCaixaNOME: TStringField;
    dspCaixa: TDataSetProvider;
    dsCaixa: TDataSource;
    qCaixaCDMOVIMENTACAO: TIntegerField;
    qCaixaMOVIMENTACAO: TStringField;
    cdsCaixaCDMOVIMENTACAO: TIntegerField;
    cdsCaixaMOVIMENTACAO: TStringField;
    qContaCliente: TSQLQuery;
    dspContaCliente: TDataSetProvider;
    cdsContaCliente: TClientDataSet;
    dsContaCliente: TDataSource;
    cdsContaClienteCDCONTA_CORRENTE: TIntegerField;
    cdsContaClienteCDCLIENTE: TIntegerField;
    cdsContaClienteCDPEDIDO: TIntegerField;
    cdsContaClienteDATA: TDateField;
    cdsContaClienteDESCRICAO: TStringField;
    cdsContaClienteDEBITO: TFMTBCDField;
    cdsContaClienteCREDITO: TFMTBCDField;
    cdsContaClienteSALDO: TFMTBCDField;
    cdsContaClienteCDUSUARIO: TIntegerField;
    qConfig_Venda: TSQLQuery;
    cdsConfig_Venda: TClientDataSet;
    dspConfig_Venda: TDataSetProvider;
    dsConfig_Venda: TDataSource;
    cdsConfig_VendaMOSTRAR_CUPOM_TELA: TIntegerField;
    cdsConfig_VendaMOSTRAR_OF: TIntegerField;
    cdsTPCDPLANO_CONTAS: TIntegerField;
    cdsTPDATA: TDateField;
    cdsTPPARCELAMENTO: TIntegerField;
    qReceber: TSQLQuery;
    cdsReceber: TClientDataSet;
    dspReceber: TDataSetProvider;
    dsReceber: TDataSource;
    cdsReceberCDCTAS_RECEBER: TIntegerField;
    cdsReceberCDPEDIDO: TIntegerField;
    cdsReceberDATA: TDateField;
    cdsReceberVALOR: TFMTBCDField;
    cdsReceberVENCIMENTO: TDateField;
    cdsReceberTIPO_VENDA: TStringField;
    cdsReceberDATA_RECEBIMENTO: TDateField;
    cdsReceberLIQUIDADO: TIntegerField;
    cdsReceberLIQUIDADO_POR: TStringField;
    cdsReceberLIQUIDADO_EM: TDateField;
    cdsReceberCDPLANO_CONTAS: TIntegerField;
    cdsReceberPARCELA: TIntegerField;
    qParcela: TSQLQuery;
    cdsParcela: TClientDataSet;
    dspParcela: TDataSetProvider;
    dsParcela: TDataSource;
    cdsParcelaVENCIMENTO: TDateField;
    cdsParcelaPARCELA: TIntegerField;
    cdsParcelaCDPLANO_CONTAS: TIntegerField;
    cdsParcelaVALOR: TFMTBCDField;
    cdsTPGRAVA_CTAS_RECEBER: TIntegerField;
    cdsParcelaCDPAGAMENTO: TIntegerField;
    cdsParcelaPAGAMENTO: TStringField;
    cdsConfig_VendaGRAVAR_COMISSAO_CTAS_PAGAR: TIntegerField;
    cdsConfig_VendaCOMISSAO_CONFORME_RECEBIMENTO: TIntegerField;
    qProdutos: TSQLQuery;
    dspProdutos: TDataSetProvider;
    cdsProdutos: TClientDataSet;
    cdsProdutosCDPRODUTO: TIntegerField;
    cdsProdutosCDFORNECEDOR: TIntegerField;
    cdsProdutosCDBARRAS: TStringField;
    cdsProdutosCDGRUPO: TIntegerField;
    cdsProdutosCDSUBGRUPO: TIntegerField;
    cdsProdutosDESCRICAO: TStringField;
    cdsProdutosVALOR_CUSTO: TSingleField;
    cdsProdutosVALOR_VENDA: TSingleField;
    cdsProdutosVALOR_CONTABIL: TSingleField;
    cdsProdutosMARGEM: TSingleField;
    cdsProdutosUNID_ENTRADA: TSingleField;
    cdsProdutosUNID_SAIDA: TSingleField;
    cdsProdutosSERVICO: TIntegerField;
    cdsProdutosIPI: TSingleField;
    cdsProdutosICMS: TSingleField;
    cdsProdutosCFOP: TStringField;
    cdsProdutosSIT_TRIBUTARIA: TStringField;
    cdsProdutosCOMISSAO: TSingleField;
    cdsProdutosDESCONTO: TSingleField;
    cdsProdutosQTD_DESCONTO: TSingleField;
    cdsProdutosAPLICACAO: TStringField;
    cdsProdutosTIPO_UN_ENTRADA: TStringField;
    cdsProdutosTIPO_UN_SAIDA: TStringField;
    cdsProdutosESTOQUE_QTD: TSingleField;
    cdsProdutosESTOQUE_MINIMO: TSingleField;
    cdsProdutosCDCENTRO_CUSTO: TIntegerField;
    cdsProdutosUSO_CONSUMO: TIntegerField;
    cdsProdutosMARCA: TStringField;
    cdsProdutosCDINTERNO: TStringField;
    cdsProdutosMODELO: TStringField;
    cdsProdutosGRUPO: TStringField;
    cdsProdutosSUBGRUPO: TStringField;
    cdsProdutosCDPLANO_CONTAS: TIntegerField;
    cdsProdutosCONTA: TStringField;
    cdsProdutosCODIGOST: TStringField;
    cdsProdutosFORNECEDOR: TStringField;
    dsProdutos: TDataSource;
    qVendedor: TSQLQuery;
    cdsVendedor: TClientDataSet;
    dspVendedor: TDataSetProvider;
    dsVendedor: TDataSource;
    qCtasPagar: TSQLQuery;
    qCtasPagarCDCTAS_PAGAR: TIntegerField;
    qCtasPagarCDFORNECEDOR: TIntegerField;
    qCtasPagarNOME: TStringField;
    qCtasPagarNUMERO_DOCUMENTO: TStringField;
    qCtasPagarDESCRICAO: TStringField;
    qCtasPagarVALOR: TFMTBCDField;
    qCtasPagarVALOR_PAGO: TFMTBCDField;
    qCtasPagarVENCIMENTO: TDateField;
    qCtasPagarDATA_PAGTO: TDateField;
    qCtasPagarFORMA_PAGTO: TStringField;
    qCtasPagarCADASTRADO_POR: TStringField;
    qCtasPagarCADASTRADO_EM: TDateField;
    qCtasPagarLIQUIDADO: TIntegerField;
    qCtasPagarLIQUIDADO_POR: TStringField;
    qCtasPagarLIQUIDADO_EM: TDateField;
    qCtasPagarCDPLANO_CONTAS: TIntegerField;
    qCtasPagarDESCRICAO_CONTA: TStringField;
    qCtasPagarCONTA: TStringField;
    qCtasPagarCDCONTA_BANCARIA: TIntegerField;
    dspCtasPagar: TDataSetProvider;
    cdsCtasPagar: TClientDataSet;
    cdsCtasPagarCDCTAS_PAGAR: TIntegerField;
    cdsCtasPagarCDFORNECEDOR: TIntegerField;
    cdsCtasPagarNUMERO_DOCUMENTO: TStringField;
    cdsCtasPagarDESCRICAO: TStringField;
    cdsCtasPagarVALOR: TFMTBCDField;
    cdsCtasPagarVALOR_PAGO: TFMTBCDField;
    cdsCtasPagarVENCIMENTO: TDateField;
    cdsCtasPagarDATA_PAGTO: TDateField;
    cdsCtasPagarFORMA_PAGTO: TStringField;
    cdsCtasPagarCADASTRADO_POR: TStringField;
    cdsCtasPagarCADASTRADO_EM: TDateField;
    cdsCtasPagarLIQUIDADO: TIntegerField;
    cdsCtasPagarLIQUIDADO_POR: TStringField;
    cdsCtasPagarLIQUIDADO_EM: TDateField;
    cdsCtasPagarCDPLANO_CONTAS: TIntegerField;
    cdsCtasPagarCONTA: TStringField;
    cdsCtasPagarNOME: TStringField;
    cdsCtasPagarDESCRICAO_CONTA: TStringField;
    cdsCtasPagarCDCONTA_BANCARIA: TIntegerField;
    dsCtasPagar: TDataSource;
    qComissao: TSQLQuery;
    dspComissao: TDataSetProvider;
    cdsComissao: TClientDataSet;
    dsComissao: TDataSource;
    qItensTMPCDPEDIDO_ITENS_TEMP: TIntegerField;
    qItensTMPCDPEDIDO_TEMP: TIntegerField;
    qItensTMPCDPRODUTO: TIntegerField;
    qItensTMPVALOR_UNITARIO: TFMTBCDField;
    qItensTMPQTD: TFloatField;
    qItensTMPVALOR_TOTAL: TFMTBCDField;
    qItensTMPSUBTOTAL: TFMTBCDField;
    qItensTMPDESCONTO: TFloatField;
    qItensTMPACRESCIMO: TFloatField;
    qItensTMPCDVENDEDOR: TIntegerField;
    qItensTMPCONTADOR: TIntegerField;
    qItensTMPDESCRICAO: TStringField;
    qItensTMPUNID_SAIDA: TFloatField;
    qItensTMPTIPO_UN_SAIDA: TStringField;
    qItensTMPCDBARRAS: TStringField;
    cdsItensTMPCDPEDIDO_ITENS_TEMP: TIntegerField;
    cdsItensTMPCDPEDIDO_TEMP: TIntegerField;
    cdsItensTMPCDPRODUTO: TIntegerField;
    cdsItensTMPVALOR_UNITARIO: TFMTBCDField;
    cdsItensTMPQTD: TFloatField;
    cdsItensTMPVALOR_TOTAL: TFMTBCDField;
    cdsItensTMPSUBTOTAL: TFMTBCDField;
    cdsItensTMPDESCONTO: TFloatField;
    cdsItensTMPACRESCIMO: TFloatField;
    cdsItensTMPCDVENDEDOR: TIntegerField;
    cdsItensTMPCONTADOR: TIntegerField;
    cdsItensTMPDESCRICAO: TStringField;
    cdsItensTMPUNID_SAIDA: TFloatField;
    cdsItensTMPTIPO_UN_SAIDA: TStringField;
    cdsItensTMPCDBARRAS: TStringField;
    qPedidosTmp: TSQLQuery;
    dspPedidosTmp: TDataSetProvider;
    cdsPedidosTmp: TClientDataSet;
    dsPedidosTmp: TDataSource;
    qPedidosTmpCDPEDIDO_TEMP: TIntegerField;
    qPedidosTmpCDVENDEDOR: TIntegerField;
    qPedidosTmpCDUSUARIO: TIntegerField;
    qPedidosTmpCDCLIENTE: TIntegerField;
    qPedidosTmpDATA: TDateField;
    qPedidosTmpHORA: TTimeField;
    qPedidosTmpDESCONTO: TFloatField;
    qPedidosTmpACRESCIMO: TFloatField;
    qPedidosTmpNF_EMITIDA: TIntegerField;
    qPedidosTmpCDPAGAMENTO: TIntegerField;
    qPedidosTmpNUMERO_PDV: TIntegerField;
    qPedidosTmpCDPLANO_CONTAS: TIntegerField;
    qPedidosTmpSUBTOTAL: TFloatField;
    qPedidosTmpVALOR_TOTAL: TFloatField;
    qPedidosTmpVALOR_PAGO: TFloatField;
    qPedidosTmpVENDEDOR: TStringField;
    qPedidosTmpCLIENTE: TStringField;
    qPedidosTmpDESCRICAO_CONTA: TStringField;
    qPedidosTmpPAGAMENTO: TStringField;
    cdsPedidosTmpCDPEDIDO_TEMP: TIntegerField;
    cdsPedidosTmpCDVENDEDOR: TIntegerField;
    cdsPedidosTmpCDUSUARIO: TIntegerField;
    cdsPedidosTmpCDCLIENTE: TIntegerField;
    cdsPedidosTmpDATA: TDateField;
    cdsPedidosTmpHORA: TTimeField;
    cdsPedidosTmpDESCONTO: TFloatField;
    cdsPedidosTmpACRESCIMO: TFloatField;
    cdsPedidosTmpNF_EMITIDA: TIntegerField;
    cdsPedidosTmpCDPAGAMENTO: TIntegerField;
    cdsPedidosTmpNUMERO_PDV: TIntegerField;
    cdsPedidosTmpCDPLANO_CONTAS: TIntegerField;
    cdsPedidosTmpSUBTOTAL: TFloatField;
    cdsPedidosTmpVALOR_TOTAL: TFloatField;
    cdsPedidosTmpVALOR_PAGO: TFloatField;
    cdsPedidosTmpVENDEDOR: TStringField;
    cdsPedidosTmpCLIENTE: TStringField;
    cdsPedidosTmpDESCRICAO_CONTA: TStringField;
    cdsPedidosTmpPAGAMENTO: TStringField;
    qPedidosTmpTIPO: TStringField;
    cdsPedidosTmpTIPO: TStringField;
    cdsComissaoCDCOMISSAO: TIntegerField;
    cdsComissaoCDVENDEDOR: TIntegerField;
    cdsComissaoCDPEDIDO: TIntegerField;
    cdsComissaoDATA: TDateField;
    cdsComissaoVENCIMENTO: TDateField;
    cdsComissaoPAGO: TIntegerField;
    cdsComissaoCADASTRADO_POR: TStringField;
    cdsComissaoCADASTRADO_EM: TSQLTimeStampField;
    cdsComissaoALTERADO_POR: TStringField;
    cdsComissaoALTERADO_EM: TSQLTimeStampField;
    cdsComissaoDATA_PAGTO: TDateField;
    cdsComissaoVALOR: TFloatField;
    cdsVendedorCDVENDEDOR: TIntegerField;
    cdsVendedorNOME: TStringField;
    cdsVendedorAPELIDO: TStringField;
    cdsVendedorREGIAO: TStringField;
    cdsVendedorENDERECO: TStringField;
    cdsVendedorNUMERO: TStringField;
    cdsVendedorBAIRRO: TStringField;
    cdsVendedorCIDADE: TStringField;
    cdsVendedorCEP: TStringField;
    cdsVendedorUF: TStringField;
    cdsVendedorCPF_CNPJ: TStringField;
    cdsVendedorRG_IE: TStringField;
    cdsVendedorNASC_FUNDACAO: TDateField;
    cdsVendedorCADASTRADO_POR: TStringField;
    cdsVendedorCADASTRADO_EM: TSQLTimeStampField;
    cdsVendedorALTERADO_POR: TStringField;
    cdsVendedorALTERADO_EM: TSQLTimeStampField;
    cdsVendedorFONE: TStringField;
    cdsVendedorCELULAR: TStringField;
    cdsVendedorCDIBGE: TFMTBCDField;
    cdsVendedorATIVO: TIntegerField;
    cdsVendedorCOD_IBGE: TStringField;
    cdsVendedorCOD_PAIS: TStringField;
    cdsVendedorPAIS: TStringField;
    cdsVendedorCOMISSAO: TFloatField;
    cdsVendedorMETA: TFloatField;
    qPedidosTmpDATA_VALIDADE: TDateField;
    cdsPedidosTmpDATA_VALIDADE: TDateField;
    qPedidosTmpDIAS_AVISO: TIntegerField;
    cdsPedidosTmpDIAS_AVISO: TIntegerField;
    qPedidosPagDATA: TDateField;
    cdsPedidosPagDATA: TDateField;
    cdsConfig_VendaIMAGEM_VENDA: TBlobField;
    cdsConfig_VendaMOSTRAR_DESCONTO_VENDA: TIntegerField;
    cdsConfig_VendaPULAR_VALOR_UNITARIO_VENDA: TIntegerField;
    qCaixaCDPEDIDO: TIntegerField;
    cdsCaixaCDPEDIDO: TIntegerField;
    cdsMovimentaCDMOVIMENTO: TIntegerField;
    cdsMovimentaCDPRODUTO: TIntegerField;
    cdsMovimentaDATA: TDateField;
    cdsMovimentaHORA: TTimeField;
    cdsMovimentaMOVIMENTO: TStringField;
    cdsMovimentaSALDO_ANTERIOR: TFloatField;
    cdsMovimentaSAIDA: TFloatField;
    cdsMovimentaSALDO_ATUAL: TFloatField;
    cdsMovimentaCDUSUARIO: TIntegerField;
    procedure cdsItensTMPAfterOpen(DataSet: TDataSet);
    procedure jvmPagamentoAfterOpen(DataSet: TDataSet);
    procedure dspPedidosTmpGetTableName(Sender: TObject; DataSet: TDataSet;
      var TableName: WideString);
    procedure dspItensTMPGetTableName(Sender: TObject; DataSet: TDataSet;
      var TableName: WideString);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DMVenda: TDMVenda;

implementation

uses Principal_p, Funcoes_p, Vendas_p, DMPrincipal_p;

{$R *.dfm}

procedure TDMVenda.cdsItensTMPAfterOpen(DataSet: TDataSet);
begin
  //TFloatField(cds.FieldByName('TOTAL')).DisplayFormat := '###,###,##0.00';
end;

procedure TDMVenda.dspItensTMPGetTableName(Sender: TObject; DataSet: TDataSet;
  var TableName: WideString);
begin
  TableName := ('PEDIDO_ITENS_TEMP');
end;

procedure TDMVenda.dspPedidosTmpGetTableName(Sender: TObject; DataSet: TDataSet;
  var TableName: WideString);
begin
  TableName := ('PEDIDOS_TEMP');
end;

procedure TDMVenda.jvmPagamentoAfterOpen(DataSet: TDataSet);
begin
  TFloatField(jvmPagamento.FieldByName('VALOR')).DisplayFormat := '###,###,##0.00';
end;

end.
