Program MRP;

uses
  Forms,
  Dialogs,
  Principal_p in 'Principal_p.pas' {Principal},
  TelaProdutos_p in 'TelaProdutos_p.pas' {TelaProdutos},
  Funcoes_p in 'Funcoes_p.pas',
  Clientes_p in 'Clientes_p.pas' {Clientes},
  Mascote_p in 'Mascote_p.pas' {Mascote},
  Fornecedores_p in 'Fornecedores_p.pas' {Fornecedores},
  Pedidos_p in 'Pedidos_p.pas' {Pedidos},
  Transportadores_p in 'Transportadores_p.pas' {Transportadores},
  Usuarios_p in 'Usuarios_p.pas' {Usuarios},
  Vendas_p in 'Vendas_p.pas' {Vendas},
  Vendas_Pagamento_p in 'Vendas_Pagamento_p.pas' {Vendas_Pagamento},
  PesquisaClientes_p in 'PesquisaClientes_p.pas' {PesquisaClientes},
  TelaSubgrupo_p in 'TelaSubgrupo_p.pas' {TelaSubgrupo},
  TelaGrupo_p in 'TelaGrupo_p.pas' {TelaGrupo},
  TelaEmpresa_p in 'TelaEmpresa_p.pas' {TelaEmpresa},
  TelaConfigAdminstrativa_p in 'TelaConfigAdminstrativa_p.pas' {TelaConfigAdministrativa},
  DMVenda_p in 'DMVenda_p.pas' {DMVenda: TDataModule},
  TelaAgendaBanhoeTosa_p in 'TelaAgendaBanhoeTosa_p.pas' {TelaAgendaBanhoeTosa},
  TelaCadastraBanho_p in 'TelaCadastraBanho_p.pas' {TelaCadastraBanho},
  TelaAgendaClinica_p in 'TelaAgendaClinica_p.pas' {TelaAgendaClinica},
  TelaVeterinarios_p in 'TelaVeterinarios_p.pas' {TelaVeterinarios},
  TelaCadastraConsulta_p in 'TelaCadastraConsulta_p.pas' {TelaCadastraConsulta},
  TelaProcedimentos_p in 'TelaProcedimentos_p.pas' {TelaProcedimentos},
  ConsultaProdutos_p in 'ConsultaProdutos_p.pas' {ConsultaProdutos},
  TelaServidor_p in 'TelaServidor_p.pas' {TelaServidor},
  TelaSobre_p in 'TelaSobre_p.pas' {TelaSobre},
  TelaFoneFornecedor_p in 'TelaFoneFornecedor_p.pas' {TelaFoneFornecedor},
  TelaRacas_p in 'TelaRacas_p.pas' {TelaRacas},
  TelaFoneClientes_p in 'TelaFoneClientes_p.pas' {TelaFoneCliente},
  DMForncedores_p in 'DMForncedores_p.pas' {DMFornecedores: TDataModule},
  TelaContatoFornecedor_p in 'TelaContatoFornecedor_p.pas' {TelaContatoFornecedor},
  DMClientes_p in 'DMClientes_p.pas' {DMClientes: TDataModule},
  TelaCadastraMascote_p in 'TelaCadastraMascote_p.pas' {TelaCadastraMascote},
  ConsultaCliente_p in 'ConsultaCliente_p.pas' {ConsultaCliente},
  TelaCadastraTosador_p in 'TelaCadastraTosador_p.pas' {TelaCadastraTosador},
  TelaAberturaCaixa_p in 'TelaAberturaCaixa_p.pas' {TelaAberturaCaixa},
  TelaCaixa_p in 'TelaCaixa_p.pas' {TelaCaixa},
  RelatorioBoletimCaixa_p in 'RelatorioBoletimCaixa_p.pas' {RelatorioBoletimCaixa},
  ConsultaProdutoVenda_p in 'ConsultaProdutoVenda_p.pas' {ConsultaProdutoVenda},
  PerguntaData_p in 'PerguntaData_p.pas' {PerguntaData},
  TelaContaCliente_p in 'TelaContaCliente_p.pas' {TelaContaCliente},
  TelaAcesso_p in 'TelaAcesso_p.pas' {TelaAcesso},
  TelaContasPagar_p in 'TelaContasPagar_p.pas' {TelaContasPagar},
  LivroCaixa_p in 'LivroCaixa_p.pas' {LivroCaixa},
  TelaMovimentacaoCaixa_p in 'TelaMovimentacaoCaixa_p.pas' {TelaMovimentacaoCaixa},
  TelaAlteraSenha_p in 'TelaAlteraSenha_p.pas' {TelaAlteraSenha},
  DMPrincipal_p in 'DMPrincipal_p.pas' {DMPrincipal: TDataModule},
  TelaVendedores_p in 'TelaVendedores_p.pas' {TelaVendedores},
  TelaCodigoSerial_p in 'TelaCodigoSerial_p.pas' {TelaCodigoSerial},
  TelaPlanoContas_p in 'TelaPlanoContas_p.pas' {TelaPlanoContas},
  PesquisaPlanoContas_p in 'PesquisaPlanoContas_p.pas' {PesquisaPlanoContas},
  PesquisaFornecedores_p in 'PesquisaFornecedores_p.pas' {PesquisaFornecedores},
  TelaSituacaoTributaria_p in 'TelaSituacaoTributaria_p.pas' {TelaSituacaoTributaria},
  TelaNaturezaOperacao_p in 'TelaNaturezaOperacao_p.pas' {TelaNaturezaOperacao},
  TelaClassificacaoFiscal_p in 'TelaClassificacaoFiscal_p.pas' {TelaClassificacaoFiscal},
  TelaConfiguracaoAgenda_p in 'TelaConfiguracaoAgenda_p.pas' {TelaConfiguracaoAgenda},
  TelaAgendamento_p in 'TelaAgendamento_p.pas' {TelaAgendamento},
  TelaAgendamentoRapido_p in 'TelaAgendamentoRapido_p.pas' {TelaAgendamentoRapido},
  Vendas2_p in 'Vendas2_p.pas' {vendas2},
  TelaNFe_p in 'TelaNFe_p.pas' {TelaNFe},
  DMNFE_p in 'DMNFE_p.pas' {DMNFE: TDataModule},
  TelaNavegador_p in 'TelaNavegador_p.pas' {TelaNavegador},
  TelaNF_p in 'TelaNF_p.pas' {TelaNF},
  TelaGeracaoNF_p in 'TelaGeracaoNF_p.pas' {TelaGeracaoNF},
  TelaOrdemServico_p in 'TelaOrdemServico_p.pas' {TelaOrdemServico},
  ListagemPlanoContas_p in 'ListagemPlanoContas_p.pas' {ListagemPlanoContas},
  ListagemFornecedores_p in 'ListagemFornecedores_p.pas' {ListagemFornecedores},
  TelaContasReceber_p in 'TelaContasReceber_p.pas' {TelaContasReceber},
  RelatorioCtasPagarPeriodo_p in 'RelatorioCtasPagarPeriodo_p.pas' {RelatorioCtasPagarPeriodo},
  RelatorioCtasPagasPeriodo_p in 'RelatorioCtasPagasPeriodo_p.pas' {RelatorioCtasPagasPeriodo},
  TelaDespesaConta_p in 'TelaDespesaConta_p.pas' {TelaDespesaConta},
  TelaColaboradores_p in 'TelaColaboradores_p.pas' {TelaColaboradores},
  TelaCargos_p in 'TelaCargos_p.pas' {TelaCargos},
  RelatorioDemosntrativoConta_p in 'RelatorioDemosntrativoConta_p.pas' {RelatorioDemonstrativoConta},
  TelaConfiguracaoTecnica_p in 'TelaConfiguracaoTecnica_p.pas' {TelaConfiguracaoTecnica},
  PesquisaVendedores_p in 'PesquisaVendedores_p.pas' {PesquisaVendedores},
  TelaConfiguracaoVenda_p in 'TelaConfiguracaoVenda_p.pas' {TelaConfiguracaoVenda},
  TelaConfiguracaoContabil_p in 'TelaConfiguracaoContabil_p.pas' {TelaConfiguracaoContabil},
  TelaOrdemCompra_p in 'TelaOrdemCompra_p.pas' {TelaOrdemCompra},
  TelaContatoCliente_p in 'TelaContatoCliente_p.pas' {TelaContatoCliente},
  TelaContatoTransportador_p in 'TelaContatoTransportador_p.pas' {TelaContatoTransportador},
  TelaOportunidadeNegocios_p in 'TelaOportunidadeNegocios_p.pas' {TelaOportunidadeNegocios},
  TelaPrazos_p in 'TelaPrazos_p.pas' {TelaPrazos},
  PesquisaTransportadores_p in 'PesquisaTransportadores_p.pas' {PesquisaTransportadores},
  PesquisaNaturezaOperacao_p in 'PesquisaNaturezaOperacao_p.pas' {PesquisaNaturezaOperacao},
  PerguntaNFe_p in 'PerguntaNFe_p.pas' {PerguntaNFe},
  DMProduto_p in 'DMProduto_p.pas' {DMProduto: TDataModule},
  PesquisaSituacaoTributaria_p in 'PesquisaSituacaoTributaria_p.pas' {PesquisaSituacaoTributaria},
  PesquisaOrigemProduto_p in 'PesquisaOrigemProduto_p.pas' {PesquisaOrigemProduto},
  PesquisaCSOSN_p in 'PesquisaCSOSN_p.pas' {PesquisaCSOSN},
  PesquisaSTIPI_p in 'PesquisaSTIPI_p.pas' {PesquisaSTIPI},
  PesquisaSTPIS_Cofins_p in 'PesquisaSTPIS_Cofins_p.pas' {PesquisaSTPIS_Cofins},
  PesquisaEnqIPI_p in 'PesquisaEnqIPI_p.pas' {PesquisaEnqIPI},
  RelatorioOC_p in 'RelatorioOC_p.pas' {RelatorioOC},
  PesquisaCondicaoPagto_p in 'PesquisaCondicaoPagto_p.pas' {PesquisaCondicaoPagto},
  TelaOrdemCompraMsg_p in 'TelaOrdemCompraMsg_p.pas' {TelaOrdemCompraMsg},
  TelaRecebeNF_p in 'TelaRecebeNF_p.pas' {TelaRecebeNF},
  PesquisaOrdemCompra_p in 'PesquisaOrdemCompra_p.pas' {PesquisaOrdemCompra},
  TelaRecebeNFVencimento_p in 'TelaRecebeNFVencimento_p.pas' {TelaRecebeNFVencimento},
  TelaSegmentoTrabalho_p in 'TelaSegmentoTrabalho_p.pas' {TelaSegmentoTrabalho},
  TelaRejeicaoNFe_p in 'TelaRejeicaoNFe_p.pas' {TelaRejeicaoNFe},
  RelatorioCtasRecebidasPeriodo_p in 'RelatorioCtasRecebidasPeriodo_p.pas' {RelatorioCtasRecebidasPeriodo},
  TelaFormaPagto_p in 'TelaFormaPagto_p.pas' {TelaFormaPagto},
  RelatorioFluxoCaixa_p in 'RelatorioFluxoCaixa_p.pas' {RelatorioFluxoCaixa},
  ListagemGrupo_p in 'ListagemGrupo_p.pas' {ListagemGrupo},
  ListagemSubGrupo_p in 'ListagemSubGrupo_p.pas' {ListagemSubGrupo},
  ListagemProdutos_p in 'ListagemProdutos_p.pas' {ListagemProdutos},
  ListagemPrazosGarantias_p in 'ListagemPrazosGarantias_p.pas' {ListagemPrazosGarantias},
  ListagemVendedores_p in 'ListagemVendedores_p.pas' {ListagemVendedores},
  ListagemClientes_p in 'ListagemClientes_p.pas' {ListagemClientes},
  TelaICMSEstado_p in 'TelaICMSEstado_p.pas' {TelaICMSEstado},
  TelaAutorizacao_p in 'TelaAutorizacao_p.pas' {TelaAutorizacao},
  RelatorioPedidos_p in 'RelatorioPedidos_p.pas' {RelatorioPedidos},
  TelaLinhaProdutos_p in 'TelaLinhaProdutos_p.pas' {TelaLinhaProdutos},
  TelaConsulta_p in 'TelaConsulta_p.pas' {TelaConsulta},
  ListagemRacas_p in 'ListagemRacas_p.pas' {ListagemRacas},
  RelatorioOrcamento_p in 'RelatorioOrcamento_p.pas' {RelatorioOrcamento},
  PerguntaOrcamento_p in 'PerguntaOrcamento_p.pas' {PerguntaOrcamento},
  ListagemLinhaProdutos_p in 'ListagemLinhaProdutos_p.pas' {ListagemLinhaProdutos},
  ListagemCargoseFuncoes_p in 'ListagemCargoseFuncoes_p.pas' {ListagemCargoseFuncoes},
  RelatorioFichaCadastral_p in 'RelatorioFichaCadastral_p.pas' {RelatorioFichaCadastral},
  TelaBanco_p in 'TelaBanco_p.pas' {TelaBanco},
  TelaSocios_p in 'TelaSocios_p.pas' {TelaSocios},
  TelaComissoes_p in 'TelaComissoes_p.pas' {TelaComissoes},
  TelaVacinas_p in 'TelaVacinas_p.pas' {TelaVacinas},
  TelaEnderecoCobranca_p in 'TelaEnderecoCobranca_p.pas' {TelaEnderecoCobranca},
  StatsClasses in 'StatsClasses.pas',
  TelaRelatoriosVendas_p in 'TelaRelatoriosVendas_p.pas' {TelaRelatoriosVendas},
  PerguntaDataUnica_p in 'PerguntaDataUnica_p.pas' {PerguntaDataUnica},
  RelatorioVendasSemanal_p in 'RelatorioVendasSemanal_p.pas' {RelatorioVendasSemanal},
  RelatorioVendasMensal_p in 'RelatorioVendasMensal_p.pas' {RelatorioVendasMensal},
  PerguntaMesAno_p in 'PerguntaMesAno_p.pas' {PerguntaMesAno},
  RelatorioVendasAnual_p in 'RelatorioVendasAnual_p.pas' {RelatorioVendasAnual},
  RelatorioAgendaSalao_p in 'RelatorioAgendaSalao_p.pas' {RelatorioAgendaSalao},
  GraficoVendasDia_p in 'GraficoVendasDia_p.pas' {GraficoVendasDia},
  TelaReceituario_p in 'TelaReceituario_p.pas' {TelaReceituario},
  TelaCompatibilidade_p in 'TelaCompatibilidade_p.pas' {TelaCompatibilidade},
  TelaCapturaXML_p in 'TelaCapturaXML_p.pas' {TelaCapturaXML},
  DMRecebeNFe_p in 'DMRecebeNFe_p.pas' {DMRecebeNFe: TDataModule},
  RelatorioMovimentacaoProduto_p in 'RelatorioMovimentacaoProduto_p.pas' {RelatorioMovimentacaoProduto},
  TelaCadastraCliente_p in 'TelaCadastraCliente_p.pas' {TelaCadastraCliente},
  TelaCustosProduto_p in 'TelaCustosProduto_p.pas' {TelaCustosProduto};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TDMPrincipal, DMPrincipal);
  Application.CreateForm(TDMVenda, DMVenda);
  Application.CreateForm(TDMFornecedores, DMFornecedores);
  Application.CreateForm(TDMClientes, DMClientes);
  Application.CreateForm(TDMNFE, DMNFE);
  Application.CreateForm(TDMProduto, DMProduto);
  Application.CreateForm(TDMRecebeNFe, DMRecebeNFe);
  Application.CreateForm(TPrincipal, Principal);
  Application.Run;
end.
